# Generated by Django 3.0 on 2020-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200815_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='slug',
            field=models.SlugField(),
        ),
    ]
