# Generated by Django 3.0 on 2020-08-16 13:54

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200815_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
