# Generated by Django 3.0 on 2020-08-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lessons_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
