# Generated by Django 3.0 on 2020-08-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200816_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='saved',
            field=models.ManyToManyField(blank=True, to='course.SavedCourse'),
        ),
    ]
