# Generated by Django 3.0 on 2020-08-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_userlibrary_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlibrary',
            name='saved',
        ),
    ]
