# Generated by Django 3.0 on 2020-08-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0002_auto_20200815_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='content_body',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
