# Generated by Django 3.0 on 2020-08-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0003_auto_20200817_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='presentation',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
