# Generated by Django 3.0.7 on 2020-10-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0005_auto_20200824_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='content_body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_completed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('name', 'slug')},
        ),
    ]
