# Generated by Django 3.0.7 on 2020-10-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0006_auto_20201005_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='details',
        ),
    ]
