# Generated by Django 2.2.10 on 2020-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0008_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
