# Generated by Django 2.2.10 on 2020-10-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0010_auto_20201006_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
