# Generated by Django 2.2.10 on 2020-10-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0012_auto_20201006_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
