# Generated by Django 2.2.10 on 2020-10-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0013_serviceform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceForm',
            new_name='Project',
        ),
    ]
