# Generated by Django 2.2.10 on 2020-10-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0014_auto_20201006_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='project_type',
        ),
    ]
