# Generated by Django 3.0.7 on 2020-10-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0017_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('why', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
    ]
