# Generated by Django 3.0.8 on 2020-08-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200808_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='author',
            new_name='user',
        ),
    ]
